# Generated by Django 4.2.3 on 2023-08-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='comment_text',
            new_name='comment',
        ),
    ]
