# Generated by Django 4.2.3 on 2023-08-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_comment_text_enquiry_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='comment',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='phone',
            new_name='email',
        ),
    ]
