# Generated by Django 4.2.3 on 2023-08-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_comment_enquiry_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='comment_text',
            new_name='comment',
        ),
    ]
