# Generated by Django 4.2.3 on 2023-08-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_email_enquiry_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='phone',
            new_name='email',
        ),
    ]
