# Generated by Django 4.2.3 on 2023-08-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_phone_enquiry_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='email',
            new_name='phone',
        ),
    ]
