# Generated by Django 4.2.3 on 2023-08-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_enquiryservice_alter_awesome_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enquiryservice',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='float',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='image',
            field=models.ImageField(default=1, upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='paragraph',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
