# Generated by Django 4.2.3 on 2023-08-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_enquiry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesome',
            name='text',
            field=models.ImageField(default=1, upload_to='photos'),
            preserve_default=False,
        ),
    ]
