# Generated by Django 4.2.3 on 2023-08-12 10:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_awesome_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awesome',
            name='text',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='text',
        ),
        migrations.AddField(
            model_name='awesome',
            name='product_details',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
