# Generated by Django 4.2.3 on 2023-08-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_remove_awesome_text_remove_enquiry_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesome',
            name='product_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
