# Generated by Django 4.2.3 on 2023-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_awesome_product_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='awesome',
            name='product_details',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
