# Generated by Django 4.2.3 on 2023-08-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_enquiry_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Email',
        ),
    ]
