# Generated by Django 4.2.3 on 2023-08-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_rename_contactmessage_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='leave_comment',
        ),
    ]
