# Generated by Django 4.2.3 on 2023-08-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_rename_comment_leave_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Art',
        ),
    ]
