# Generated by Django 4.2.3 on 2023-08-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_delete_art'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leave_comment',
        ),
    ]
