# Generated by Django 4.2 on 2023-09-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_servicedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servicedetails',
            new_name='serviceForm',
        ),
    ]
