# Generated by Django 4.2 on 2023-09-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_rename_servicedetails_serviceform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serviceForm',
            new_name='service_conact',
        ),
    ]
