# Generated by Django 4.2 on 2023-09-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_rename_service_conact_serviceform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceform',
            name='Phone',
            field=models.CharField(max_length=100),
        ),
    ]
