# Generated by Django 4.2 on 2023-09-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_serviceform_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serviceform',
            new_name='Service_Enquiry',
        ),
    ]
