# Generated by Django 4.2 on 2023-09-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_rename_serviceform_service_enquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Enquiry',
            new_name='form',
        ),
    ]
