# Generated by Django 4.2 on 2023-09-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_rename_service_enquiry_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='Enquiry_Form',
        ),
    ]
