# Generated by Django 4.2 on 2023-12-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_rename_enquiry_form_enquiryform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Email'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiry'},
        ),
        migrations.AlterModelOptions(
            name='enquiryform',
            options={'verbose_name': 'EnquiryForm', 'verbose_name_plural': 'EnquiryForm'},
        ),
    ]
